### PR TITLE
Vendor BearSSL sources (same commit as the submodule)

### PR DESCRIPTION
**Pull request by der-teufel-programming**
This allows other packages to depend on zig-bearssl using zig's pm. It will be possible to remove vendored sources once https://github.com/ziglang/zig/issues/14298 gets resolved

### CODE REVIEW

**Review by ikskuh — APPROVED** [review]

**Comment by ikskuh** [comment]
Trusting you on this

**Comment by stef** [comment]
> This allows other packages to depend on zig-bearssl using zig's pm. It will be possible to remove vendored sources once [ziglang/zig#14298](https://github.com/ziglang/zig/issues/14298) gets resolved

it is resolved: https://github.com/ziglang/zig/pull/17277

**Comment by stef** [comment]
damn, the upstream bearssl.org server only supports tlsv1.[012] and zig fetch only tlsv1.3.

**Comment by stef** [comment]
i have to say i prefer submodules over vendored deps, with submodules you don't have to actually get the original upstream and compare it with the vendored one for any deviations - be them innocent or malicious. vendored libs thus create much more effort for the conscious user...

**Comment by stef** [comment]
i just did a diff between the vendored version and upstream #HEAD. the diff is substantial: https://ctrlc.hu/~stef/diff-vendored-upstream.patch

**Comment by stef** [comment]
see also https://github.com/ikskuh/zig-bearssl/pull/11

**Pull request merged**
